config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  get 'chat', to: 'chats#chat'

  post '/checkname', to: 'users#checkname'
  # get "users/:id", to: "profiles#show", as: "profile"
  resources :profiles, only: [:show, :edit]
  resources :users, :chats, :photos

  resources :posts do
    member do
      post 'upvote', to: "posts#upvote"
      post 'downvote', to: "posts#downvote"
    end
  end

  resources :comments do
    get 'upvote'
    get 'downvote'
  end

  resources :comments, only: [:show, :edit, :update]

  resources :chats

  get 'slideshow', to: 'posts#slider'

  resources :posts do
    resources :comments, only: [:index, :new, :create, :destroy]
  end

  get 'photo/index'

  get 'dashboard/index'

  root to: 'dashboard#index'

  namespace :admin do
    resources :profiles, only: [:index]
    resources :postmans
    post 'sender/:id', to: 'postmans#sender', as: 'sender'
  end

  post 'contact_send', to: 'store#contact_send'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :vote_comments, dependent: :destroy

  t = '/system/:class/:attachment/:id_partition/:style/:hash.:extension'

  has_attached_file :image,
                    styles: {
                      original: '1024x1024>',
                      medium: '640x',
                      thumb: ['120x120#', :jpg]
                    },
                    path: ':rails_root/public:url',
                    url: t,
                    hash_secret: Rails.application.secrets.secret_paperclip

  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}

  def upvote(profile)
    update_attribute(:rating, self.rating + 1)
    profile.update_attribute(:rating, profile.rating + 1)
  end

  def downvote(profile)
    update_attribute(:rating, self.rating - 1)
    profile.update_attribute(:rating, profile.rating - 1)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html
  respond_to :js

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save!
    redirect_to :back

    # respond_to do |format|
    #  if @comment.save
    #    format.html { redirect_to @comment, notice: 'Comment created.' }
    #    format.json { render :show, status: :created, location: @comment }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @comment.errors,
    # status: :unprocessable_entity }
    #  end
    # end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post = Post.friendly.find(params[:post_id])
    @comment.destroy
    redirect_to :back # TODO redirect in case of jump to prev page
    # respond_to do |format|
    #  format.html { redirect_to comments_url, notice: 'Comment destroyed.' }
    #  format.json { head :no_content }
    # end
  end

  def upvote
    if current_user
      @comment = Comment.find(params[:comment_id])
      profile = Profile.find(@comment.user_id)
      unless comment_voted?(@comment) # user isn't allowed to vote twice
        @vote_comment = current_user.vote_comments.build(value: 1, comment: @comment)
        @vote_comment.save
        @comment.upvote(profile)
      end
      respond_with(@comment)
    else
      render js: "window.location = '#{new_user_session_path}';"
    end
  end

  def downvote
    if current_user
      @comment = Comment.find(params[:comment_id])
      profile = Profile.find(@comment.user_id)
      unless comment_voted?(@comment)
        @vote_comment = current_user.vote_comments.build(value: -1, comment: @comment)
        @vote_comment.save
        @comment.downvote(profile)
      end
      respond_with(@comment)
    else
      render js: "window.location = '#{new_user_session_path}';"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :image)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_voted?(comment)
    if current_user && VoteComment.find_by_user_id_and_comment_id(current_user.id, comment.id)
        VoteComment.find_by_user_id_and_comment_id(current_user.id, comment.id).value
    end
  end
end

app/views/comments/_comment.html.slim
- @comments.each do |comment|
 .row
    .col-sm-2
        = comment.user.name ? comment.user.name : "NoName"
    .col-sm-8.col-xs-12.comment-wrapper
      = l(comment.created_at, format: :short)
      - if comment_voted?(comment) == 1 || comment_voted?(comment).nil?
        .comment-up
          = link_to image_tag('thumb_up25.png'), comment_upvote_path(comment),
            remote: true, class: ("opacity4" if comment_voted?(comment) == 1)
      .comment-counter = comment.rating
      - if comment_voted?(comment) == -1 || comment_voted?(comment).nil?
        .comment-down
          = link_to image_tag('thumb_down25.png'), comment_downvote_path(comment),
            remote: true, class: ("opacity4" if comment_voted?(comment) == -1)
      .comment-body
        p
          = comment.content
        = link_to image_tag(comment.image.url(:medium)), comment.image.url, :target => "_blank" if comment.image_file_name
      .darkline
        -if current_user && comment.user.id == current_user.id || current_user && current_user.admin?
          =link_to t(:delete_comment), [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning btn-xs sharp pull-right"
        /=link_to 'Reply', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success btn-xs sharp pull-right"
        /=link_to 'Edit', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info btn-xs sharp pull-right"

app/views/comments/_form.html.slim
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.association :post
    = f.input :content

  .form-actions
    = f.button :submit

app/views/comments/_new.html.slim
.row
  .col-sm-10.col-sm-offset-1
    #addComment.text-center
      -if current_user
        h4 = t(:add_comment)
        = simple_form_for([@post, @post.comments.build], html: { multipart: true }) do |f|
          = f.text_area :content
          p
            = f.file_field :image, class: 'btn'
          p
            = f.submit t(:add_comment), class: 'btn btn-success btn-xs'
      -else
        = t('registration.text',
          to_login: link_to(t('registration.to_login'), new_user_session_path),
          to_register: link_to(t('registration.to_register'), new_user_registration_path)).html_safe

app/views/comments/downvote.js.erb
<% if current_user %>
  $('div#<%= dom_id(@comment) %>').
    replaceWith('<%= j render "comment", comment: @comment %>');
<% else %>
  alert("<%= "#{t(:login_first)}" %>")
<% end %>

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/upvote.js.erb
<% if current_user %>
  $('div#<%= dom_id(@comment) %>').
    replaceWith('<%= j render "comment", comment: @comment %>');
<% else %>
  alert("<%= "#{t(:login_first)}" %>")
<% end %>