config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  get 'chat', to: 'chats#chat'

  post '/checkname', to: 'users#checkname'
  # get "users/:id", to: "profiles#show", as: "profile"
  resources :profiles, only: [:show, :edit]
  resources :users, :chats, :photos

  resources :posts do
    member do
      post 'upvote', to: "posts#upvote"
      post 'downvote', to: "posts#downvote"
    end
  end

  resources :comments do
    get 'upvote'
    get 'downvote'
  end

  resources :comments, only: [:show, :edit, :update]

  resources :chats

  get 'slideshow', to: 'posts#slider'

  resources :posts do
    resources :comments, only: [:index, :new, :create, :destroy]
  end

  get 'photo/index'

  get 'dashboard/index'

  root to: 'dashboard#index'

  namespace :admin do
    resources :profiles, only: [:index]
    resources :postmans
    post 'sender/:id', to: 'postmans#sender', as: 'sender'
  end

  post 'contact_send', to: 'store#contact_send'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Concerns::Roles

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  devise :database_authenticatable,
    :registerable,
    :omniauthable,
    :recoverable,
    :rememberable,
    :trackable,
    :validatable,
    :confirmable,
    authentication_keys: [:login]

  validates_format_of :email, without: TEMP_EMAIL_REGEX, on: :update
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :posts, dependent: :destroy
  has_many :identities, dependent: :destroy
  has_many :vote_posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :vote_comments, dependent: :destroy

  after_create :create_profile

  attr_accessor :login

  def self.search(name)
    where('name = ?', name).first if name
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(['lower(name) = :value OR lower(email) = :value', { value: login.downcase }]).first
    else
      if conditions[:name].nil?
        where(conditions).first
      else
        where(name: conditions[:name]).first
      end
    end
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      email_is_verified = auth.info.email && (
        auth.info.verified || auth.info.verified_email
      )
      email = auth.info.email # if email_is_verified
      user = User.where(email: email).first if email

      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0, 20],
          avatar_file_name: auth.info.image,
          avatar_updated_at: Time.now,
          facebook_name: auth.extra.raw_info.name
        )
        user.skip_confirmation!
        user.save!
        user
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    email && email !~ TEMP_EMAIL_REGEX
  end

  def facebook_uid
    identity = Identity.where(id: 1)
    identity.uid
  end

  def set_admin
    update_attribute(:role, :admin)
  end

  def create_profile
      Profile.create(user: self)
      profile = Profile.last
      profile.update_attribute(:rating, 0)
  end

  def voted_for_post?(post)
    self.vote_posts.find_by_post_id(post.id).value if self.vote_posts.find_by_post_id(post.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_admin, only: [:index]
  before_action :authenticate_user!, only: [:show, :edit]
  before_action :set_user, only: [:show,
                                  :edit,
                                  :update,
                                  :destroy,
                                  :finish_signup
                                 ]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, bypass: true)
        format.html { redirect_to @user, notice: 'Your profile was updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish_signup
    # authorize! :update, @user
    current_user.skip_confirmation!
    if request.patch? && params[:user] # && params[:user][:email]
      if current_user.update(user_params)
        current_user.skip_confirmation!
        sign_in(current_user, bypass: true)
        redirect_to root_path, notice: t(:profile_updated)
      else
        @show_errors = true
      end
    end
  end

  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was deleted.' }
      format.json { head :no_content }
    end
  end

  def checkname
    @user = User.search(params[:name])
    respond_to do |format|
      format.json {render json: {name_exists: @user.present?}}
  end
end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [:name, :email, :role]
    accessible << [:password, :password_confirmation] unless
      params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user)
    user.avatar_file_name.blank? ? nil : user.avatar_file_name
  end
end

app/views/users/_form.html.slim
= form_for @user, html: { class: "form form-horizontal user" } do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control'
    = f.label :email, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :email
    = f.label :last_sign_in_at, class: 'control-label col-lg-2'
    .col-lg-10
      = f.datetime_select :last_sign_in_at
    = f.label :role, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :role
  .actions = f.submit nil, class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h4><%= t(:confirm_email) %></h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, autofocus: true, value: '', class: 'form-control input-lg', placeholder: t(:Example_email) %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit t(:finish_registration), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.slim
h1 Listing users
table.table.table-striped.table-responsive
  thead
    tr
      th.col-md-1 Name
      th.col-md-3 Email
      th.col-md-1 Role
      th.col-md-1 Current IP
      th.col-md-1 Last IP
      th.col-md-1 LastSignIn
      th.col-md-1 SignIn count
      th.col-md-1
      th.col-md-1
      th.col-md-1

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = user.role
        td = user.current_sign_in_ip
        td = user.last_sign_in_ip
        td = user.current_sign_in_at
        td = user.sign_in_count
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path