config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  get 'chat', to: 'chats#chat'

  post '/checkname', to: 'users#checkname'
  # get "users/:id", to: "profiles#show", as: "profile"
  resources :profiles, only: [:show, :edit]
  resources :users, :chats, :photos

  resources :posts do
    member do
      post 'upvote', to: "posts#upvote"
      post 'downvote', to: "posts#downvote"
    end
  end

  resources :comments do
    get 'upvote'
    get 'downvote'
  end

  resources :comments, only: [:show, :edit, :update]

  resources :chats

  get 'slideshow', to: 'posts#slider'

  resources :posts do
    resources :comments, only: [:index, :new, :create, :destroy]
  end

  get 'photo/index'

  get 'dashboard/index'

  root to: 'dashboard#index'

  namespace :admin do
    resources :profiles, only: [:index]
    resources :postmans
    post 'sender/:id', to: 'postmans#sender', as: 'sender'
  end

  post 'contact_send', to: 'store#contact_send'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :caption, use: :slugged

  validates :image, presence: true
  validates :caption, presence: true

  has_attached_file :image,
    styles: { original: '1024x1024>',
              medium: '640x',
              thumb: ['120x120#', :jpg]
            },
    path: ':rails_root/public:url',
    url: '/system/:class/:attachment/:id_partition/:style/:hash.:extension',
    hash_secret: Rails.application.secrets.secret_paperclip

  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}

  belongs_to :user
  has_many :vote_posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def upvote(current_user, post)
    vote_post = current_user.vote_posts.build(value: 1, post: post)
    vote_post.save
    update_attribute(:rating, self.rating + 1)
    profile = Profile.find(post.user_id)
    profile.update_attribute(:rating, profile.rating + 1)
  end

  def downvote(current_user, post)
    vote_post = current_user.vote_posts.build(value: -1, post: post)
    vote_post.save
    update_attribute(:rating, self.rating - 1)
    profile = Profile.find(post.user_id)
    profile.update_attribute(:rating, profile.rating - 1)
  end

  def self.best
    order(rating: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  attr_accessor :vote_btn_class

  before_action :set_post, only: [:destroy, :show, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :upvote, :downvote, :show]
  before_action :get_vote_btn_class
  after_action :send_news_email, only: [:create]

  respond_to :html
  respond_to :js

  def index
    @posts_best = Post.best
    @paginate = Post.paginate(
      page: params[:page], per_page: 5
    ).order(created_at: :desc)
    if current_user
      @posts = @paginate.all if current_user.admin? || current_user.family?
      @posts = @paginate.where(family: 0).all if current_user.user?
    else
      @posts = @paginate.where(family: 0).all
    end
  end

  def upvote
    unless current_user.nil? || current_user.voted_for_post?(@post)
      @post.upvote current_user, @post
    else
      head :ok, content_type: "text/html" if current_user
      render js: "window.location = '#{new_user_session_path}';" unless current_user
    end
  end

  def downvote
    unless current_user.nil? || current_user.voted_for_post?(@post)
      @post.downvote current_user, @post
    else
      head :ok, content_type: "text/html" if current_user
      render js: "window.location = '#{new_user_session_path}';" unless current_user
    end
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: t(:post_created)
    else
      redirect_to new_post_path
    end
  end

  def destroy
    @post.destroy
  end

  def slider
    @posts = Post.all
  end

  def show
    @comments = @post.comments.paginate(page: params[:page], per_page: 10).
      order(created_at: :asc)
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption, :family)
  end

  def set_post
    @post = Post.friendly.find(params[:id])
    if @post.family?
      redirect_to root_path, notice: t(:access_denied) if current_user && current_user.role == 'user'
      redirect_to root_path, notice: t(:access_denied) unless current_user
    end
  end

  def get_vote_btn_class
    current_user ? @vote_btn_class = 'btn_vote' : @vote_btn_class = 'btn_vote opacity4'
  end

  def send_news_email
    arel_table = Profile.arel_table
    profiles_to_email = Profile.where(arel_table['news_email_sent_at'].lt(3.days.ago).
      or(arel_table['news_email_sent_at'].eq(nil)))

    profiles_to_email.each do |profile|
      @user = User.find(profile.id)
      next if @user == current_user || @user.user?
      UserMailer.news_email(@user, Post.last).deliver_later
      profile.update_attribute(:news_email_sent_at, Time.now)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  
end

app/views/posts/_post.html.slim
= div_for post do
  .post-rating
    = button_to '+', upvote_post_path(post), remote: true, class: (current_user && current_user.voted_for_post?(post) == 1 ? @vote_btn_class + ' voted_pos' : @vote_btn_class )
    .counter
      p = post.rating
    = button_to '-', downvote_post_path(post), remote: true, class: (current_user && current_user.voted_for_post?(post) == -1 ? @vote_btn_class + ' voted_neg' : @vote_btn_class )
  .float-left.who_posted
    = t(:published_by) + ' '
    |
    mark.blue = post.user.name
    = when_posted(post.created_at)
  = link_to image_tag(post.image.url(:medium), alt: post.caption), post.image.url(:original), popup: ['original_image', 'height=700,width=900'], target: '_blank'
  .after-post
    p = post.caption + ' (' + t('posts.comments_count', count: post.comments.count) + ')'
    -if user_signed_in? && current_user.id == post.user_id || user_signed_in? && current_user.email == Rails.application.secrets.admin_email
      = link_to t(:delete_post), post_path(post), remote: true, method: :delete, class: 'btn btn-warning btn-responsive', type: 'button', data: { confirm: "#{t(:delete_post)}?" }
    = link_to t(:read_post), post_path(post), class: 'pull-right'

app/views/posts/_posts_best.html.slim
-posts_best.each do |post|
  .image.center-block-
    .counter-top-images
      = post.rating
    = link_to image_tag(post.image.url(:thumb), alt: post.caption), post_path(post)

app/views/posts/destroy.js.erb
$('div#<%= dom_id(@post) %>').fadeOut(1000);

app/views/posts/downvote.js.erb
<% if current_user %>
  $('div#<%= dom_id(@post) %>').replaceWith('<%= j render "post", post: @post %>');
<% else %>
  alert("<%= "#{t(:login_first)}" %>")
<% end %>

app/views/posts/index.html.slim
#posts.row
  #posts-sidebar.col-md-2.col-sm-2
    p = link_to t(:new_post), new_post_path, class: "btn btn-success btn-responsive", type: "button"
    -if current_user && current_user.admin?
      p = link_to t(:SlideShow), slideshow_path, class: "page-scroll btn btn-success", type: "button"
    #slideshow-container
      #slideshow
        #slideshow-reel
          - @posts.each do |post|
            .slide = image_tag post.image.url
  .col-md-7.col-sm-7.col-xs-9
    -@posts = @posts.paginate(page: params[:page], per_page: 5).order('id DESC')
    = will_paginate(@posts, renderer: 'BootstrapPagination::Rails')
    - @posts.each do |post|
      = render post
    = will_paginate(@posts, renderer: 'BootstrapPagination::Rails')
  #top-images.col-md-3.col-sm-3.col-xs-3
    span = t(:best_photos)
    p
    = render partial: 'posts_best', object: @posts_best

app/views/posts/new.html.slim
#add-post.row
  .col-sm-8.col-sm-offset-2.col-xs-12
    h3 = t(:new_post)
    = simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f|
      .form-group
        = f.label t(:choose_picture)
        = f.file_field :image, class: 'btn'
      .form-group.text-center
        = f.input :caption, label: t(:description), input_html: {maxlength: 90, placeholder: t(:type_caption)}
      .form-group.text-center
        = f.input :family if current_user.family? || current_user.admin?
      .form-group.text-center
        = f.submit t(:load_post), class: 'btn-success'

app/views/posts/show.html.slim
.row
  .col-sm-12.text-center
    = will_paginate(@comments, renderer: 'BootstrapPagination::Rails',
      inner_window: 2, outer_window: 1)
  .col-sm-12
    .row
      .col-sm-2
        = @post.user.name
      .first-post.col-sm-8.col-xs-12
        h4 = link_to @post.caption, url_for
        = link_to image_tag(@post.image.url(:medium), alt: @post.caption),
          @post.image.url(:original), popup: ['original_image', 'height=700,width=900']
    br
    = render 'comments/comment'
    br
  .col-sm-12.text-center
    = will_paginate(@comments, renderer: 'BootstrapPagination::Rails',
      inner_window: 2, outer_window: 1)
= render partial: 'comments/new'
= link_to '', '#page-top', id: 'back-to-top-link', class: 'height0'
br

app/views/posts/slider.html.erb
<div id="sl_wrapper">
		<div id="content">
			<div id="slider" class="span">
				<% i = 0; @posts.each do |post| %>
		  		<div class="img <%= "image-#{i+=1}" %>">
		  		  <%= image_tag post.image.url(:medium) %>
	      	</div>
				<% end %>
				<div class="nav previous"></div>
				<div class="nav next"></div>
				<div class="previews">
					<div class="preview previous-image"></div>
					<div class="preview next-image"></div>
				</div>
			</div>
			<div id="dots">
				<ul></ul>
			</div>
			<div class="features">
				<p> </p>
			</div>
		</div>
</div>

app/views/posts/upvote.js.erb
$('div#<%= dom_id(@post) %>').replaceWith('<%= j render "post", post: @post %>');