config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  get 'chat', to: 'chats#chat'

  post '/checkname', to: 'users#checkname'
  # get "users/:id", to: "profiles#show", as: "profile"
  resources :profiles, only: [:show, :edit]
  resources :users, :chats, :photos

  resources :posts do
    member do
      post 'upvote', to: "posts#upvote"
      post 'downvote', to: "posts#downvote"
    end
  end

  resources :comments do
    get 'upvote'
    get 'downvote'
  end

  resources :comments, only: [:show, :edit, :update]

  resources :chats

  get 'slideshow', to: 'posts#slider'

  resources :posts do
    resources :comments, only: [:index, :new, :create, :destroy]
  end

  get 'photo/index'

  get 'dashboard/index'

  root to: 'dashboard#index'

  namespace :admin do
    resources :profiles, only: [:index]
    resources :postmans
    post 'sender/:id', to: 'postmans#sender', as: 'sender'
  end

  post 'contact_send', to: 'store#contact_send'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/admin/postmans_controller.rb
class Admin::PostmansController < ApplicationController

  before_action :set_template, only: [:destroy, :show, :edit, :update, :sender]
  before_action :check_if_admin

  def index
    @mailtemplates = MailTemplate.all
  end

  def show
  end

  def edit
  end

  def update
    if @mailtemplate.update(template_params)
			redirect_to admin_postmans_path, notice: 'Template updated!'
		else
			render 'edit'
		end
  end

  def sender
    if current_user && current_user.admin?
      user = User.find_by_id(@mailtemplate.recipient)
      AccountMailer.notify(@mailtemplate, user).deliver_now
      redirect_to :back, notice: 'Email sent'
    else
      redirect_to :back, notice: 'You\'re not an admin!'
    end
  end

  def new
    @mailtemplate = MailTemplate.new
  end

  def create
    @mailtemplate = MailTemplate.new(template_params)
    if @mailtemplate.save
      redirect_to admin_postmans_path, notice: 'Template saved!'
    else
      flash[:alert] = 'U got an error!'
      render 'new'
    end
  end

  def destroy
    @mailtemplate.destroy
		redirect_to admin_postmans_path, notice: 'Template deleted!'
  end

  private

  def set_template
    @mailtemplate = MailTemplate.find(params[:id])
  end

  def template_params
    params.require(:mail_template).permit(:body, :description, :subject,
      :locale, :handler, :format, :recipient)
  end
end

app/controllers/postmans_controller.rb
class PostmansController < ApplicationController

  before_action :set_template, only: [:destroy, :show, :edit, :update, :sender]
  before_action :authenticate_user!

  def index
    @mailtemplates = MailTemplate.all
  end

  def show
  end

  def edit
  end

  def update
    if @mailtemplate.update(template_params)
			redirect_to postmans_path, notice: 'Template updated!'
		else
			render 'edit'
		end
  end

  def sender
    if current_user && current_user.admin?
      user = User.find_by_id(@mailtemplate.recipient)
      AccountMailer.notify(@mailtemplate, user).deliver_now
      redirect_to :back, notice: 'Email sent'
    else
      redirect_to :back, notice: 'You\'re not an admin!'
    end
  end

  def new
    @mailtemplate = MailTemplate.new
  end

  def create
    @mailtemplate = MailTemplate.new(template_params)
    if @mailtemplate.save
      redirect_to postmans_path, notice: 'Template saved!'
    else
      render 'new'
    end
  end

  def destroy
    @mailtemplate.destroy
		redirect_to postmans_path, notice: 'Template deleted!'
  end

  private

  def set_template
    @mailtemplate = MailTemplate.find(params[:id])
  end

  def template_params
    params.require(:mail_template).permit(:body, :description, :subject,
      :locale, :handler, :format, :recipient)
  end
end

app/views/admin/postmans/edit.html.slim
h4 = 'Edit template ' + @mailtemplate.description

= simple_form_for @mailtemplate, url: admin_postman_path do |f|
  = f.input :description
  = f.input :subject
  = f.input :body, as: :text
  br
  = f.select(:recipient, options_from_collection_for_select(User.all, :id, :email))
  = f.input :locale
  = f.input :handler
  = f.input :format

  = f.submit 'Save template', class: 'btn btn-success'
  p
= link_to 'Back', :back

app/views/admin/postmans/index.html.slim
table.table.table-striped
  thead
    tr
      th Description
      th Subject
      th Body
      th Recipient
      th
      th
      th
      th
  tbody
    - @mailtemplates.each do |template|
      tr
        td = template.description
        td = template.subject
        td = template.body
        td = template.recipient
        td = link_to 'Show', admin_postman_path(template)
        td = link_to 'Edit', edit_admin_postman_path(template)
        td = link_to 'Destroy', admin_postman_path(template), data: {confirm: 'Are you sure?'}, method: :delete
        td = link_to 'Send', admin_sender_path(template), method: :post

= button_to 'New Template', new_admin_postman_path, class: 'btn-success', method: :get

app/views/admin/postmans/new.html.slim
h4 New Template

= simple_form_for @mailtemplate, url: admin_postmans_path do |f|
  = f.input :description
  = f.input :subject
  = f.input :body, as: :text
  br
  = f.select(:recipient, options_from_collection_for_select(User.all, :id, :email))
  = f.input :locale
  = f.input :handler
  = f.input :format

  = f.submit 'Save template', class: 'btn btn-success'
  p
= link_to 'Back', :back

app/views/admin/postmans/show.html.slim
.container
  .col-sm-10.col-sm-offset-1.col-lg-8.col-lg-offset-2
    h4.text-center Mail template
    .col-sm-8
      p = 'Description: ' + @mailtemplate.description
      p = 'Subject: ' + @mailtemplate.subject
      p = 'Body: ' + @mailtemplate.body
      p = 'Recipient: ' + = @mailtemplate.recipient

= link_to 'Back', :back